---
title: "sleep and intergroup bias"
author: "Jinxiao Zhang"
date: "`r Sys.time()`"
output: html_document
---

## load packages
```{r load library, warning=FALSE}
library(foreign)
library(kableExtra)
#library(ez)
library(lsr) # for calculating eta-squared
library(lme4)
library(BayesFactor)
library(cowplot)
library(tidyverse)
```

## import data
```{r import data}
#load study 1 data
data1 <- read.spss("study 1_data.sav", to.data.frame=T)

#load study 2 data
data2 <- read.spss("study 2_data.sav", to.data.frame=T)

```

## Set plot theme
```{r set the theme}
theme_set(
  theme_classic()
)
```


# Study 1
## Study 1 analysis
```{r Study 1}
# show the descriptives
data1 %>% 
  select(PSQI_slp_dur, # sleep duration
         IAT_D600, # IAT D600 score
         BA_P_CN, # number of positive behaviors assigned to Chinese Mainlanders
         BA_N_CN # number of negative behaviors assigned to Chinese Mainlanders
         ) %>% 
  psych::describe()

# t-test of IAT D600 score to 0
t.test(data1$IAT_D600, mu = 0)

# correlations
cor.test(y = data1$IAT_D600, x = data1$ID_CN)
    correlationBF(y = data1$IAT_D600, x = data1$ID_CN) # Bayes version
cor.test(y = data1$IAT_D600, x = data1$PSQI_slp_dur)
    correlationBF(y = data1$IAT_D600, x = data1$PSQI_slp_dur) # Bayes version

#### behavior attribution bias task ####
# paired t-test between positive and negative behaviors assigned to Chinese Mainlanders
t.test(data1$BA_P_CN, data1$BA_N_CN, paired = T)
    
# the sleep x CNID linear model
mod1_s1 <- lm(BA_bias ~ PSQI_slp_dur*ID_CN, data = data1) 
mod1_s1 %>% anova()
mod1_s1 %>% etaSquared()# get the effect sizes (eta-squared)
# results: group * CNID interaction: F(1,164)=5.78, p= .017, partial eta-squared = .034.

# Simple slope tests
# simple slope of CNID at long sleep duration: beta= -.383, p< .001.
data1$ZPSQI_slp_dur_h = scale(data1$PSQI_slp_dur) - 1
lm(scale(BA_bias) ~ ZPSQI_slp_dur_h*scale(ID_CN), data = data1) %>% summary()
# simple slope of CNID at short sleep duration: beta= -.068, p= .491.
data1$ZPSQI_slp_dur_l = scale(data1$PSQI_slp_dur) + 1
lm(scale(BA_bias) ~ ZPSQI_slp_dur_l*scale(ID_CN), data = data1) %>% summary()

# estimate the means based on the model
mod1_s1_z <- lm(BA_bias ~ ZID_CN*ZPSQI_slp_dur, data = data1) 
# create prediction data -  "1": 1 SD above the mean; "-1": 1 SD below the mean
data1_prediction = data.frame(ZID_CN = rep(c(1, -1), 2),
                              ZPSQI_slp_dur = c(1, 1, -1, -1)) 
# predict the mean and 95% confidence intervals
predict(mod1_s1_z, data1_prediction, interval="confidence") %>% 
  as.tibble() %>% 
  bind_cols(arg1 = data1_prediction, arg2 = .)
```

## Study 1 visualization
```{r Plotting Study 1}
# get the coefficients from the interaction lm
study1_coef <- mod1_s1 %>% coef()

slp_dur_mean = mean(data1$PSQI_slp_dur)
slp_dur_sd = sd(data1$PSQI_slp_dur)

## Figure 1c
# plot the interaction continuously
p3_s1 <- ggplot(data1, 
       aes(ID_CN, BA_bias, fill = PSQI_slp_dur))+
  geom_hline(yintercept = 0, linetype = 2, alpha = .5)+
  geom_point(size = 3, 
             color = "grey",
             shape = 21,
             alpha = .7)+
  scale_fill_gradient2(midpoint= mean(data1$PSQI_slp_dur), 
                       low="blue", mid="white",high="red", 
                       space ="Lab",
                       name = "sleep duration")+
  geom_abline(intercept = study1_coef[1] + study1_coef[2]*(slp_dur_mean - slp_dur_sd),
              slope = study1_coef[3] + study1_coef[4]*(slp_dur_mean - slp_dur_sd),
              color = "blue", size = 1, alpha = .5)+
  geom_abline(intercept = study1_coef[1] + study1_coef[2]*(slp_dur_mean + slp_dur_sd),
              slope = study1_coef[3] + study1_coef[4]*(slp_dur_mean + slp_dur_sd),
              color = "red", size = 1, alpha = .5)+
  annotate("text", x = 5.7, y = -.15, 
           label = "beta == '-.383'", parse = TRUE)+
  annotate("text", x = 5.7, y = .2, 
           label = "beta == '-.068'", parse = TRUE)+
  labs(title = "c. Bias Score Scatter Plot",
    x = "CNID", 
    y = "Intergroup bias score")


## Figure 1a
p1_s1 <- ggplot(data1, aes(x = PSQI_slp_dur))+
  geom_histogram(binwidth = .5,
                 color = "black",
                 fill = "white")+
  labs(title = "a. Histogram of Sleep Duration",
       x = "sleep duration")+
  geom_vline(xintercept = c(slp_dur_mean - slp_dur_sd,
                            slp_dur_mean,
                            slp_dur_mean + slp_dur_sd),
             linetype = 2)+
  annotate("text", x = c(5.2, 6.95, 8.8), y = c(43, 43, 43), 
           label = c("-1 SD", "mean", "+1 SD"))


## Figure 1b
CNID_mean = mean(data1$ID_CN)
CNID_sd = sd(data1$ID_CN)

p2_s1 <- ggplot(data1, aes(x = ID_CN))+
  geom_histogram(bins = 10,
                 color = "black",
                 fill = "white")+
  labs(title = "b. Histogram of Chinese Identity",
       x = "CNID")+
  geom_vline(xintercept = c(CNID_mean - CNID_sd,
                            CNID_mean,
                            CNID_mean + CNID_sd),
             linetype = 2)+
  annotate("text", x = c(1.9, 3.5, 4.9), y = c(46, 46, 46), 
           label = c("-1 SD", "mean", "+1 SD"))

# build the top row
top_row <- plot_grid(p1_s1, p2_s1)
bottom_row <- plot_grid(p3_s1, NULL, rel_widths = c(3, 1))
# then combine with the top row for final plot
plot_grid(top_row, bottom_row, ncol = 1, rel_heights = c(3, 4))

ggplot2::ggsave(filename = "figures/Figure1.pdf", width = 8, height = 7)
```

## Study 1 supplementary analysis

```{r last-night sleep}
df.study1 <- read.spss("C:/Users/tepzh/Dropbox/1CUHK-shared folder 2017-2019/Research projects_ongoing/GRF Research with Sheen Levine/DATA/Public Goods_20180607.sav",
                       to.data.frame=T) %>% 
  filter(PSQI_check == 1) %>% 
  mutate(SubjectID = as.character(SubjectID))

df.study1 <- df.study1 %>% 
  mutate(diary_sleep_dur = (last_wake_hr - last_sleep_hr) + 
           (last_wake_min - last_sleep_min)/60 - wake_min/60) %>% 
  mutate(diary_sleep_dur = ifelse(diary_sleep_dur < 0, 
                                  diary_sleep_dur+24, diary_sleep_dur),
         BA_bias = (IB_N_CN - IB_P_CN)/(IB_N_CN + IB_P_CN))

hist(df.study1$diary_sleep_dur)
hist(df.study1$BA_bias)

```

```{r PSQI and diary sleep}

cor.test(df.study1$PSQI_Q4a, df.study1$diary_sleep_dur)

ggplot(df.study1, aes(PSQI_Q4a, diary_sleep_dur))+
  geom_point(alpha = .5)+
  geom_smooth(method = "lm")+
  geom_abline(slope = 1, intercept = 0, linetype = 2)+
  xlim(0, 10)+ ylim(0, 10)+
  annotate("text", x = 0.5, y = 10, label = "r = .20")
```

```{r diary sleep and intergroup bias}
# test the interaction model
lm(scale(BA_bias) ~ scale(diary_sleep_dur)*scale(ID_CN), data = df.study1) %>% 
  summary()
```

```{r coffee use}
hist(df.study1$coffee_cups)
table(df.study1$coffee_cups)
```

```{r trial-level logistic model}
df.study1_BA <- df.study1 %>% 
  select(SubjectID, PSQI_Q4a, ID_CN, IB_P1:IB_Neu7) %>% 
  gather(BA_item, choice, IB_P1:IB_Neu7) %>% 
  mutate(BA_type = ifelse(grepl("IB_P", BA_item), "positive",
                          ifelse(grepl("IB_Neu", BA_item), "neutral",
                                 "negative"))) %>% 
  mutate(choice_num = ifelse(choice == "Chinese Mainlanders", 1, 0),
         slp_dur = PSQI_Q4a,
         slp_dur_scaled = scale(slp_dur),
         BA_type_num = ifelse(BA_type == "positive", 1, 
                              ifelse(BA_type == "negative", -1, 0)),
         ID_CN_scaled = scale(ID_CN))


# the trial-level logistic model
# need to scale continuous variables, otherwise the model doesn't converge
mod_trial1_data1 <- glmer(choice_num ~ slp_dur_scaled*ID_CN_scaled*BA_type + 
                            (1|SubjectID) + (1|BA_item),
                        data = df.study1_BA %>% 
                          filter(BA_type %in% c("positive", "negative")), 
                        family = binomial)

summary(mod_trial1_data1)

# positive behaviors
glmer(choice_num ~ slp_dur_scaled*ID_CN_scaled + 
                            (1|SubjectID) + (1|BA_item),
                        data = df.study1_BA %>% 
                          filter(BA_type %in% c("positive")), 
                        family = binomial) %>% 
  summary()
# negative behaviors
glmer(choice_num ~ slp_dur_scaled*ID_CN_scaled + 
                            (1|SubjectID) + (1|BA_item),
                        data = df.study1_BA %>% 
                          filter(BA_type %in% c("negative")), 
                        family = binomial) %>% 
  summary()
```

```{r plot the trial-level model predictions}
## construct the dataframe to predict
df.trial_to_predict_study1 = data.frame(slp_dur_scaled = rep(rep(c(-1, 1),each = 2), 200),
                                 BA_type = rep(rep(c("positive", "negative"), 2), 200),
                                 ID_CN_scaled = rep(seq(-2, 2, length.out = 200), 
                                                    each = 4))

# calculate the predicted log-odds and probability
df.trial_predicted_study1 <- mod_trial1_data1 %>% 
  predict(newdata = df.trial_to_predict_study1, re.form = NA) %>%  # set the random effect to 0
  as.data.frame() %>% 
  set_names("predicted_logodds") %>% 
  bind_cols(df.trial_to_predict_study1) %>% 
  mutate(predicted_p = boot::inv.logit(predicted_logodds),
         ID_CN = ID_CN_scaled*sd(df.study1_BA$ID_CN)+mean(df.study1_BA$ID_CN),
         slp_dur_label = ifelse(slp_dur_scaled == 1, 
                                "long sleep duration", "short sleep duration"))

# plot the prediction
p_trial_model_study1 <- df.trial_predicted_study1 %>% 
  ggplot(aes(ID_CN, predicted_p, color = BA_type))+
  geom_line(size = 1, alpha = .7)+
  facet_grid(.~slp_dur_label)+
  labs(x = "Chinese Identity", 
       y = "p(Chinese Mainlanders)",
       color = "behavior")+
  ylim(0, 1)+
  theme_classic()
ggsave("figures/Figure S1.png", width = 6, height = 3)
```





# Study 2

## Study 2 analysis
```{r Study 2}
## manipulation check
# present the descriptives
data2 %>% 
  group_by(group) %>% 
  summarise(mean_Day1_smin = mean(Day1_smin), # smin - actigraph sleep minutes
            sd_Day1_smin = sd(Day1_smin),
            mean_Day2_smin = mean(Day2_smin, na.rm = T),
            sd_Day2_smin = sd(Day2_smin, na.rm = T),
            mean_SSS = mean(main_SSS), # main_SSS: Stanford Sleepiness Scale on Day3
            sd_SSS = sd(main_SSS)
            ) %>% 
  kable()
# t-tests between the 2 groups
t.test(data2$Day1_smin~data2$group, var.equal = T) #sleep time on Day 1
t.test(data2$main_SSS~data2$group, var.equal = T) # SSS on Day 3


## Social Identity
# present the descriptives of CNID
data2 %>% 
  group_by(group) %>% 
  summarise(mean_CNID = mean(ID_CN),
            sd_CNID = sd(ID_CN)
            ) %>% 
  kable()
# t-test
t.test(data2$ID_CN~data2$group, var.equal = T) # CNID
# correlation between CNID and HKID
cor.test(data2$ID_CN,data2$ID_HK)


## IAT
# present the descriptives of IAT D600 scores
data2 %>% 
  group_by(group) %>% 
  summarise(mean_day1_IAT = mean(pre_IAT_D600, na.rm = T),
            sd_day1_IAT = sd(pre_IAT_D600, na.rm = T),
            mean_day3_IAT = mean(main_IAT_D600, na.rm = T),
            sd_day3_IAT = sd(main_IAT_D600, na.rm = T)
            ) %>% 
  kable()
# t-test on pre-IAT D600
t.test(pre_IAT_D600~group, var.equal = T, data = data2)
# t-test on Day-3 IAT D600
t.test(main_IAT_D600~group, data = data2, var.eq = T)
    # BF version
    ttestBF(formula = main_IAT_D600~group, 
            data = data2 %>% filter(!is.na(main_IAT_D600)))
# correlations
cor.test(data2$ID_CN, data2$pre_IAT_D600)
cor.test(data2$ID_CN, data2$main_IAT_D600)


#### behavior attribution bias task ####
# show the descriptives
data2 %>% 
  select(BA_P_CN, BA_N_CN) %>% 
  psych::describe()
# paired t-test between positive and negative behaviors assigned to Chinese Mainlanders
t.test(data2$BA_P_CN, data2$BA_N_CN, paired = T)

# the Group x CNID linear model on the bias score of Behavior Attribution Bias Task
mod1_data2 <- lm(BA_bias ~ group*ID_CN, data = data2)
anova(mod1_data2) 
etaSquared(mod1_data2) # get the effect sizes (eta-squared)
# results: group * CNID interaction: F(1,63)=3.95, p = .051, partial eta-squared = .059.

# Simple slope tests
# simple slope of CNID in the control group: beta= -.510, p= .005.
lm(scale(BA_bias) ~ group*scale(ID_CN), data = data2) %>% summary()
# simple slope of CNID in the deprivation group: beta= -.034, p= .837.
data2$group_t = factor(data2$group, levels = c("sleep deprivation", "sleep control"))
lm(scale(BA_bias) ~ group_t*scale(ID_CN), data = data2) %>% summary()

```




```{r Plotting BA_task, echo=FALSE}
## Figure 2a
data2$group <- factor(data2$group, labels = c("control", "deprived"))

# plotting bias score in Study 2, Behavior Attribution Bias Task
p1 <- ggplot(data2, aes(ID_CN, BA_bias, 
                        color = group,
                        fill = group))+
  geom_hline(yintercept = 0, linetype = 2, alpha = .5)+
  geom_line(stat="smooth", method = "lm",  
              fullrange = T, alpha = .5, size = 1)+
  geom_point(shape = 21,
             size = 3,
             alpha = .4,
             color = "grey")+
  scale_color_manual(values = c("red", "blue"))+
  scale_fill_manual(values = c("red", "blue"))+
  labs(title = "a. Bias Score",
    x = "CNID", 
    y = "Intergroup bias score")+
  annotate("text", x = 5.4, y = -.5, 
           label = "beta == '-.510'", parse = TRUE)+
  annotate("text", x = 5.4, y = .08, 
           label = "beta == '-.034'", parse = TRUE)+
  #ggthemes::theme_few()+
  theme_classic()+
  theme(legend.position = "bottom",
        legend.title = element_blank(),
        legend.text = element_text(size = 12),
        axis.text = element_text(color = "black",
                                 size = 12),
        axis.title = element_text(color = "black",
                                  face = "plain",
                                  size = 12),
        legend.margin=margin(0,0,0,0),
        legend.box.margin=margin(-5,0,0,0),
        plot.title = element_text(face = "bold", hjust = .5))

## Figure 2b
# plotting positive and negative behaviors in Study 2, Behavior Attribution Bias Task
# transform data2 for lmer
data2_long <- data2 %>% 
  select(participant, group, ID_CN, BA_P_CN, BA_N_CN) %>% 
  gather(behavior_type, number, BA_P_CN, BA_N_CN) %>% 
  mutate(behavior = ifelse(behavior_type == "BA_P_CN", "positive", "negative"),
         participant = as.character(participant),
         ZID_CN = scale(ID_CN))

# linear mixed-effect model for raw number of positive and negative behaviors
mod2_data2 <- lmer(number ~ group*ZID_CN*behavior + (1|participant), data = data2_long)

# generate a data.frame which we would like to predict based on the model
data_predict <- data.frame(group = c(rep("control", 4), rep("deprived", 4)),
                      ZID_CN = rep(c(1,-1), 4),
                      behavior = rep(c(rep("positive", 2), rep("negative", 2)), 2),
                      participant = sample(data2$participant, 8) #sample participants randomly
                      )
# predict the values from the fitted lmer
data_predict_result <- merTools::predictInterval(mod2_data2, newdata = data_predict, 
                          n.sims = 1000, level = 0.95, stat = 'mean', # 95% interval
                          include.resid.var = F, which = "fixed") %>% # only predict the fixed effect
  bind_cols(data_predict) %>% 
  mutate(CNID = ifelse(ZID_CN == 1, "high CNID", "low CNID"))

data_predict_result$behavior <- factor(data_predict_result$behavior,
                                         level = c("positive", "negative"))
data_predict_result$CNID <- factor(data_predict_result$CNID,
                                         level = c("low CNID", "high CNID"))


p2 <- ggplot(data_predict_result, aes(CNID, y=fit, 
                                      ymin=lwr, ymax=upr, 
                                      fill = behavior))+
  geom_bar(stat = "identity", 
           color = "black",
           width = .5,
           position = position_dodge(.6))+
  geom_errorbar(#aes(ymin= mean - CI, ymax= mean + CI),
                width = .2,
                position = position_dodge(.6))+
  labs(title = "b. Number of Behaviors",
       x = "Control                       Deprived",
       y = "Number of behaviors assigned to\n Chinese Mainlanders")+
  scale_fill_manual(values = c("white", "dimgrey"))+
  facet_wrap(. ~ group)+
  #ggthemes::theme_few()+
  theme_classic()+
  scale_y_continuous(breaks = seq(0,7,1), limits = c(0, 7))+
  theme(legend.position = "bottom",
        legend.direction = "horizontal",
        legend.title = element_blank(),
        legend.margin=margin(0,0,0,0),
        legend.box.margin=margin(-5,0,0,0),
        legend.text = element_text(size = 12),
        axis.text = element_text(color = "black",
                                 size = 12),
        axis.title = element_text(color = "black",
                                  face = "plain",
                                  size = 12),
        strip.text = element_blank(),
        plot.title = element_text(face = "bold", hjust = .5)
        )

plot_grid(p1, NULL, p2, nrow = 1, rel_widths = c(3.5, .5, 4))
ggplot2::ggsave(filename = "figures/Figure2.pdf", width = 10, height = 5)

```

## Study 2 supplementary analysis
```{r PVT}
df.study2 <- read.spss("C:/Users/tepzh/Dropbox/1CUHK-shared folder 2017-2019/Research projects_ongoing/Sleep and intergroup bias/data/SD-intergroup bias data_combined_20180723.sav", to.data.frame = T)

df.study2_pvt <- df.study2 %>% 
  select(Sub_ID, group, contains("PVT")) %>% 
  mutate(PVT_RT_change = main_PVT_RT - pre_PVT_RT,
         PVT_miss_change = main_PVT_miss - pre_PVT_miss)

# check the distributional information of PVT changes in the two groups
psych::describeBy(df.study2_pvt, group = df.study2_pvt$group)

t.test(PVT_RT_change ~ group, data = df.study2_pvt)
t.test(PVT_miss_change ~ group, data = df.study2_pvt)

```

```{r trial-level logistic model}
df.study2_BA <- df.study2 %>% 
  select(Sub_ID, group, ID_CN, IB_P1:IB_Neu7) %>% 
  gather(BA_item, choice, IB_P1:IB_Neu7) %>% 
  mutate(BA_type = ifelse(grepl("IB_P", BA_item), "positive",
                          ifelse(grepl("IB_Neu", BA_item), "neutral",
                                 "negative"))) %>% 
  mutate(choice_num = ifelse(choice == "Chinese Mainlanders", 1, 0),
         group_num = ifelse(group == "sleep deprivation", 1, 0),
         BA_type_num = ifelse(BA_type == "positive", 1, 
                              ifelse(BA_type == "negative", -1, 0)),
         ID_CN_scaled = scale(ID_CN))


# the trial-level logistic model
# need to scale continuous variables, otherwise the model doesn't converge
mod_trial1_data2 <- glmer(choice_num ~ group*ID_CN_scaled*BA_type + 
                            (1|Sub_ID) + (1|BA_item),
                        data = df.study2_BA %>% 
                          filter(BA_type %in% c("positive", "negative")), 
                        family = binomial)

summary(mod_trial1_data2)


# sleep-control group
glmer(choice_num ~ scale(ID_CN)*BA_type + (1|Sub_ID) + (1|BA_item),
                        data = df.study2_BA %>% 
        filter(BA_type %in% c("positive", "negative"), group == "sleep control"), 
                        family = binomial) %>% 
  summary()
# sleep-deprivation group
glmer(choice_num ~ scale(ID_CN)*BA_type + (1|Sub_ID) + (1|BA_item),
                        data = df.study2_BA %>% 
        filter(BA_type %in% c("positive", "negative"),group == "sleep deprivation"), 
                        family = binomial) %>% 
  summary()

# Alternatively, using the brm model
mod_trial1_data2_brm <- brm(choice_num ~ group_num*ID_CN*BA_type +
                              (1|Sub_ID) + (1|BA_item),
                        data = df.study2_BA %>% 
                          filter(BA_type %in% c("positive", "negative")), 
                        family = binomial)

mod_trial1_data2_brm %>% print()
mod_trial1_data2_brm %>% plot()
```

```{r visualize the trial-level data}
ggplot(df.study2_BA %>% filter(BA_type %in% c("positive", "negative")),
       aes(ID_CN, choice_num))+
  geom_point(alpha = .1)+
  geom_smooth(method = "glm",
              method.args = list(family = "binomial"))+
  facet_grid(BA_type~group)+
  labs(x = "Chinese Identity", y = "Probability of choosing Chinese Mainlanders")

```

```{r plot the trial-level model prediction}
## construct the dataframe to predict
df.trial_to_predict = data.frame(group = rep(rep(c("sleep control", 
                                                       "sleep deprivation"),
                                                 each = 2), 200),
                                 BA_type = rep(rep(c("positive", "negative"), 2), 200),
                                 ID_CN_scaled = rep(seq(-2, 2, length.out = 200), 
                                                    each = 4))

# calculate the predicted log-odds and probability
df.trial_predicted <- mod_trial1_data2 %>% 
  predict(newdata = df.trial_to_predict, re.form = NA) %>%  # set the random effect to 0
  as.data.frame() %>% 
  set_names("predicted_logodds") %>% 
  bind_cols(df.trial_to_predict) %>% 
  mutate(predicted_p = boot::inv.logit(predicted_logodds),
         ID_CN = ID_CN_scaled*sd(df.study2_BA$ID_CN)+mean(df.study2_BA$ID_CN))

# plot the prediction
p_trial_model_study2 <- df.trial_predicted %>% ggplot(aes(ID_CN, predicted_p, color = BA_type))+
  geom_line(size = 1, alpha = .7)+
  facet_wrap(.~group)+
  labs(x = "Chinese Identity", 
       y = "p(Chinese Mainlanders)",
       color = "behavior")+
  ylim(0, 1)+
  theme_classic()
ggsave("figures/Figure S2.png", width = 6, height = 3)


plot_grid(p_trial_model_study1, p_trial_model_study2,
          ncol = 1)
ggsave("figures/Figure S3.pdf", width = 8, height = 8)


```

